server:
  port: 3030
spring:
  application:
    name: payment-api-service
  kafka:
    bootstrap-servers: localhost:19092
  cloud:
    function:
      definition: paymentEventConsumer
    stream:
      bindings:
        paymentEventConsumer-in-0:
          destination: payment-events
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      connection-timeout: 2000
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show_sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
